GET http://127.0.0.1:8080/coffees

###

POST http://127.0.0.1:8080/coffees 
Content-Type: application/json;

{
  "id": "1454",
  "name": "말차라떼11"
}

###

GET http://127.0.0.1:8080/coffees/1454

###

PUT http://127.0.0.1:8080/coffees/1454
Content-Type: application/json;

{
    "id": "1454",
    "name": "gd녹차라떼"
}

###

DELETE http://127.0.0.1:8080/coffees/1454